### ISSUE TITLE
No output after inserting API key

### ISSUE THREAD

**Issue by hananbeer** [AbanteAI/rawdog#11]
I am on windows at the moment. is it supported?
after it requests my API key I see no output and cannot enter cli mode.

there is no --help either or anything else I can see.

**Comment by AI-IntegratedSolutions** [comment]
I loaded my using the command export OPENAI_API_KEY=<YOUR APIKEY> before running rawdog and it works for me.

**Comment by tikendraw** [comment]
> I am on windows at the moment. is it supported? after it requests my API key I see no output and cannot enter cli mode.
> 
> there is no --help either or anything else I can see.

1. Locate rawdog folder and config.yaml file inside it . Add you api key. 
2. Try `rawdog`
