### ISSUE TITLE
Not working with api gpt 3.5?

### ISSUE THREAD

**Issue by qvazar1987** [AbanteAI/rawdog#13]
Hi,

I had to type in my API Key from gpt 3.5 and it seems not to work properly.
Is any chance to change the config?

C:\Users\Alex>rawdog How much space do I have on the c:?
API Key (None) not found.
Enter API Key (e.g. OpenAI): sk******

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Error:
 {'model': 'gpt-4', 'prompt': 'PROMPT: How much space do I have on the c:?', 'response': None, 'cost': None, 'error': "OpenAIException - Error code: 404 - {'error': {'message': 'The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}"}
Error: Execution error: OpenAIException - Error code: 404 - {'error': {'message': 'The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

Best regards

**Comment by clarenceehsu** [comment]
After reading the source code, there should be a `~/.rawdog/config.yaml` that contains your configs, and this file would be loaded and applied while running the rawdog.

You can simply append `llm_model: gpt-3.5-turbo` to it for enabling GPT 3.5.

**Comment by qvazar1987** [comment]
> You can simply append `llm_model: gpt-3.5-turbo` to file `~/.rawdog/config.yaml` for enabling GPT 3.5.

Hi, thanks, I have just edited my config, now I have this:

llm_api_key: mykey
llm_base_url: https://api.openai.com/v1
llm_custom_provider: openai
llm_model: gpt-3.5-turbo


But I am facing some issues:
What can I do for you? (Ctrl-C to exit)
> cd C:


Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Error:
 {'model': 'gpt-3.5-turbo', 'prompt': 'PROMPT: cd C:', 'response': None, 'cost': None, 'error': "OpenAIException - Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}"}
Error: Execution error: OpenAIException - Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}


If I access my chatgpt account I can't confirm any restrictions. I can easily chat with my account and it does not provide any information about an exceeded quota.
What is the problem with api?

Thank you
Best regards

**Comment by jakethekoenig** [comment]
I updated the readme.
