### ISSUE TITLE
Azure OpenAI API

### ISSUE THREAD

**Issue by jamie93201** [AbanteAI/rawdog#29]
How to config with Azure OpenAI?

**Comment by jamie93201** [comment]
OK,I fixed it

llm_api_key: 
llm_base_url: https://test.openai.azure.com/
llm_custom_provider: azure
llm_model: TESTmodel

and go to "llm_client.py"

response = completion(
                base_url=self.base_url,
                api_key=self.api_key,
                model=self.model,
                messages=messages,
                api_version='2023-07-01-preview',                <---add this one
                temperature=1.0,
                custom_llm_provider=self.custom_provider,

**Comment by jakethekoenig** [comment]
Thanks for reporting. I updated the readme. It doesn't say exactly what to do but it points to litellm which has good docs for [azure](https://docs.litellm.ai/docs/providers/azure).
