### ISSUE TITLE
How can I use Rawdog and LM Studio together?

### ISSUE THREAD

**Issue by zinwelzl** [AbanteAI/rawdog#32]
Do you have instruction how to connect RawDog and LM Studion?

**Comment by biobootloader** [comment]
I haven't tried LM Studio but it looks like it can run an OpenAI-compatible local server. So set that up, and then set the `llm_base_url` and `llm_model` like you would for litellm:

<img width="875" alt="image" src="https://github.com/AbanteAI/rawdog/assets/128252497/d03afbf4-2c2b-4333-a880-26bc58146b3c">

(from https://github.com/AbanteAI/rawdog?tab=readme-ov-file#model-selection)
