### ISSUE TITLE
I get this error on Windows 10 "AttributeError: module 'os' has no attribute 'uname'. Did you mean: 'name'?"

### ISSUE THREAD

**Issue by jonatj** [AbanteAI/rawdog#39]
I've successfully installed and used 'rawdog' on my personal workstation at home. But when I installed and ran it on my corporate workstation I get the error:

AttributeError: module 'os' has no attribute 'uname'. Did you mean: 'name'?

My quick google suggests that this has to do with Windows not using the 'os.uname' method but instead should use 'platform.name'.

Is there a way to make sure 'rawdog' is using the Windows method?

Thanks in advanced!

**Comment by jonatj** [comment]
I should point out that i also got this error first:

ModuleNotFoundError: No module named 'readline'

But this error was fixed by:

pip install pyreadline

**Comment by biobootloader** [comment]
Just merged a fix! https://github.com/AbanteAI/rawdog/pull/40

Let me know if that works for you. If you installed with pip it's not updated there yet - if you clone the repo you could test it

**Comment by jonatj** [comment]
Cool! Thank you! I'll give this a try.

**Comment by jonatj** [comment]
I'm sorry to ask. How do I run 'rawdog' after I've cloned the repo?  There's no executable in the folders.

**Comment by jakethekoenig** [comment]
`pip install -e .` (you may want to do this in a venv). Then you should be able to run rawdog.

**Comment by jonatj** [comment]
Thanks for that. I ran the pip install -e . in the git cloned folder and it installed without issue.  But I still get this error:

(venv) PS C:\Temp\rawdog> rawdog How many files are in this directory?
C:\Temp\rawdog\src\rawdog\__main__.py:64: SyntaxWarning: invalid escape sequence '\_'
  /_____/   U    Rawdog v{__version__}"""
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Temp\venv\Scripts\rawdog.exe\__main__.py", line 4, in <module>
  File "C:\Temp\rawdog\src\rawdog\__main__.py", line 5, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'

**Comment by biobootloader** [comment]
ah, seems `readline` is a python module that's not available on windows.

You fixed it before with `pip install pyreadline`, does that work? I'll look into options to make this work for everyone

**Comment by jonatj** [comment]
Okay, I made some progress. I installed the pyreadline3 (need the version 3):

 pip install --trusted-host pythonhosted.org --trusted-host files.pythonhosted.org pyreadline3

Then I saw another error with 'pkg_resources':

(venv) PS C:\Temp\rawdog> pip install --trusted-host pythonhosted.org --trusted-host files.pythonhosted.org pyreadline3
Collecting pyreadline3
  Using cached pyreadline3-3.4.1-py3-none-any.whl (95 kB)
Installing collected packages: pyreadline3
Successfully installed pyreadline3-3.4.1
(venv) PS C:\Temp\rawdog> rawdog How many files are in this directory?
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Temp\venv\Scripts\rawdog.exe\__main__.py", line 4, in <module>
  File "C:\Temp\rawdog\src\rawdog\__main__.py", line 9, in <module>
    from rawdog.llm_client import LLMClient
  File "C:\Temp\rawdog\src\rawdog\llm_client.py", line 9, in <module>
    from litellm import completion, completion_cost
  File "C:\Temp\venv\Lib\site-packages\litellm\__init__.py", line 520, in <module>
    from .utils import (
  File "C:\Temp\venv\Lib\site-packages\litellm\utils.py", line 32, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

The 'pkg_resources' is in setuptools, so I:

pip install --trusted-host pythonhosted.org --trusted-host files.pythonhosted.org setuptools wheel

Then when I run rawdog. It actually starts kind of. But I get a huge wall of error text and at the bottom saying "

"openai.APIConnectionError: Connection error."

The wall of error messages shows a lot of self-signed certificate errors and SSL: CERTIFICATE_VERIFY_FAILED messages.

So I think my current problem is due to our firewall acting as man-in-the-middle with our corporate certs.  There is some troubleshooting I found related to it, but it will take awhile to figure out what to do. There is a way to disable Python cert verification, that's why I was using the --trusted-host flags when installing. But now that rawdog is reaching out to OpenAI, I have no way of 'trusting' that URL.

**Comment by kvaky** [comment]
> ah, seems `readline` is a python module that's not available on windows.
> 
> You fixed it before with `pip install pyreadline`, does that work? I'll look into options to make this work for everyone

requirements.txt:
pyreadline3==3.4.1; platform_system == "Windows"

But can't test it myself as I'm on mac

**Comment by biobootloader** [comment]
@jonatj does it work when you're not on the corporate firewall?

**Comment by jonatj** [comment]
Yes, it works perfectly on my home computer (Windows 11). So I know it’s just our corporate network affected this. I also don’t have administrator rights on my work computer, but I’m not sure that is related. I’m really bummed because I love the functionality of Rawdog and wanted everyone to use it on my team. On Feb 8, 2024, at 12:03 PM, biobootloader ***@***.***> wrote:﻿
@jonatj does it work when you're not on the corporate firewall?

**Comment by man-im-unoriginal-af** [comment]
> I've successfully installed and used 'rawdog' on my personal workstation at home. But when I installed and ran it on my corporate workstation I get the error:
> 
> AttributeError: module 'os' has no attribute 'uname'. Did you mean: 'name'?
> 
> My quick google suggests that this has to do with Windows not using the 'os.uname' method but instead should use 'platform.name'.
> 
> Is there a way to make sure 'rawdog' is using the Windows method?
> 
> Thanks in advanced!

Being a Windows-exclusive error, 
`host = os.uname()[1]`

had to be changed to:
`host = os.name`

That's the fix.
