### ISSUE TITLE
RawDog without OpenAI's ChatGPT

### ISSUE THREAD

**Issue by Simatwa** [AbanteAI/rawdog#45]
I must acknowledge that indeed **rawdog** is a masterpiece. However, it's dependency on OpenAI as the main LLM provider is a kinda drawback to me, if I was to be asked. This reason actually fueled the motive to implement the rawdog idea on the the freely available LLM providers such as Aura, Phind, You etcetra. I thought by sharing [python-tgpt](https://github.com/Simatwa/python-tgpt) here, someone would find it useful. Thank you.

**Comment by biobootloader** [comment]
Rawdog already supports local models, see here: https://github.com/AbanteAI/rawdog?tab=readme-ov-file#model-selection
